config/routes.rb
Rails.application.routes.draw do
  root 'artwork#index'
  get 'artwork/details'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/artwork.rb
class Artwork
  include HTTParty

  base_uri 'https://api.artic.edu'
  default_params fields: 'id,api_link,title,image_id,artist_display,date_display,main_reference_number,description,thumbnail,place_of_origin'

  def self.searchArtwork(search)
    get "/api/v1/artworks/search?q=#{search}&limit=100"
  end

  def self.getArtDetail(id)
    get "/api/v1/artworks/#{id}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/artwork_controller.rb
class ArtworkController < ApplicationController
  def index
    # @artwork = Artwork.all
    @search_param = params[:search]
    @searchresult = Artwork.searchArtwork(@search_param)
  end

  def details
    @id = params[:id]
    @data = Artwork.getArtDetail(@id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artwork_helper.rb
module ArtworkHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/views/artwork/details.html.erb
<%= stylesheet_link_tag('details.css') %>
<div class="container">
  <div class="row" id="margin">
    <div class="col-sm-3 bold">Title</div>
    <div class="col-sm-9"><%= @data['data']['title'] %></div>
  </div>

  <div class="row" id="margin">
    <div class="col-sm-3 d-flex justify-content-center align-items-center center-div bold">Painting</div>
    <div class="col-sm-9">
      <% if @data['data']['image_id'] %>
        <%= image_tag('https://www.artic.edu/iiif/2/' + @data['data']['image_id'] + '/full/843,/0/default.jpg', class:'img-fluid') %>
      <% else %>
        <p>No Art available</p>
      <% end %>
    </div>
  </div>

  <div class="row" id="margin">
    <div class="col-sm-3 bold">Artist</div>
    <div class="col-sm-9">
      <% if @data['data']['artist_display'] %>
        <%= @data['data']['artist_display'] %>
      <% else %>
        <p>Not Available</p>
      <% end %>
    </div>
  </div>

  <div class="row" id="margin">
    <div class="col-sm-3 bold">Place of Origin</div>
    <div class="col-sm-9">
      <% if @data['data']['place_of_origin'] %>
        <%= @data['data']['place_of_origin'] %>
      <% else %>
        <p>Not Available</p>
      <% end %>
    </div>
  </div>

  <div class="row" id="margin">
    <div class="col-sm-3 bold">Year</div>
    <div class="col-sm-9">
      <% if @data['data']['date_display'] %>
        <%= @data['data']['date_display'] %>
      <% else %>
        <p>Not Available</p>
      <% end %>
    </div>
  </div>

  <div class="row" id="margin">
    <div class="col-sm-3 d-flex justify-content-center align-items-center center-div bold">Description</div>
    <div class="col-sm-9">
      <% if @data['data']['description'] %>
        <%= @data['data']['description'] %>
      <% else %>
        <p>No Data Available</p>
      <% end %>
    </div>
  </div>
</div>

app/views/artwork/index.html.erb
<%= stylesheet_link_tag('index.css') %>
<div class="container">
  <div class="table-responsive">
    <table class="table table-striped table-auto">
      <tr>
        <th>ID</th>
        <th>TITLE</th>
        <th>ART</th>
        <th>DETAIL</th>
      </tr>
      <% @searchresult['data'].each do |art| %>
        <tr>
          <td>
            <%= art['id'] %>
          </td>
          <td class="justify-content-center align-items-center center-div">
            <%= art['title'] %>
          </td>
          <td>
            <% if art['image_id'] %>
              <%= image_tag('https://www.artic.edu/iiif/2/' + art['image_id'] + '/full/843,/0/default.jpg', style: 'height:100px; width:100px;') %>
            <% else %>
              <p>No image available</p>
            <% end %>
          </td>
          <td>
            <%= link_to artwork_details_path(id: art['id']), class: "btn btn-primary" do %>
              View
            <% end %>
          </td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Assignment3ArtworkApi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <header class="d-flex justify-content-center align-items-center center-div">
    <h1>Art Institute of Chicago</h1>
  </header>
    <%= yield %>
  </body>
</html>